POST http://localhost:3333/subscriptions
Content-Type: application/json

{
    "name": "Indicado 1",
    "email": "indicado1@mail.com",
    "referrer": "18189e49-3fe6-4c41-a44d-fa206306c57e"
}

###

GET http://localhost:3333/invites/18189e49-3fe6-4c41-a44d-fa206306c57e

###

GET http://localhost:3333/subscribers/18189e49-3fe6-4c41-a44d-fa206306c57e/ranking/clicks

###
GET http://localhost:3333/subscribers/18189e49-3fe6-4c41-a44d-fa206306c57e/ranking/count

###
GET http://localhost:3333/subscribers/18189e49-3fe6-4c41-a44d-fa206306c57e/ranking/position

###
GET http://localhost:3333/ranking